---
# This playbook setups a local environment and can be used to maintain a local environment.

- name: Setup Local Env
  hosts: windows
  gather_facts: no
    
  tasks:
    - name: Install Git
      win_chocolatey:
        name: git
        state: present
    - name: Install Git Fork
      win_chocolatey:
        name: git-fork
        state: present
    - name: Install notepadplusplus
      win_chocolatey:
        name: notepadplusplus
        state: present      
    - name: Install Visual Studio Code
      win_chocolatey:
        name: vscode
        state: present
    - name: Install Google Chrome
      win_chocolatey:
        name: googlechrome
        state: present
    - name: Install IIS (Web-Server and Web-Common-Http)
      win_optional_feature:
        name:
        - IIS-WebServerRole
        state: present
    - name: Install Spotify
      win_chocolatey:
        name: spotify
        state: present
    # The following commands can be a bit slow since they do depend on outside resources (that can be slow or big), and need to be downloaded
    # Uncomment if you wish to install and run or update them
    # - name: Install PowerShell Core
    #   raw: iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI -Quiet"
    # - name: Install all security, critical, and rollup updates without a scheduled task
    #   win_updates:
    #     category_names:
    #       - SecurityUpdates
    #       - CriticalUpdates
    #       - UpdateRollups
    # - name: Install Microsoft Subsystem for Linux
    #   win_optional_feature:
    #     name: Microsoft-Windows-Subsystem-Linux
    #     state: present
    #   register: wsl_status
    #  - name: Run remote PowerShell Script
    #    win_command: powershell.exe -ExecutePolicy ByPass -File c:/temp/powershellscirpt.ps1