---
# This playbook setups a local environment and can be used to maintain a local environment.

- name: Setup Local Env
  hosts: windows
  tasks:
    - name: Install Git
      win_chocolatey:
        name: git
        state: present
    - name: Install notepadplusplus
      win_chocolatey:
        name: notepadplusplus
        state: present      
    - name: Install Visual Studio Code
      win_chocolatey:
        name: vscode
        state: present
    - name: Install Google Chrome
      win_chocolatey:
        name: googlechrome
        state: present
    - name: Install IIS (Web-Server and Web-Common-Http)
      win_optional_feature:
        name:
        - IIS-WebServerRole
        state: present
    # - name: Install Microsoft Subsystem for Linux
    #   win_optional_feature:
    #     name: Microsoft-Windows-Subsystem-Linux
    #     state: present
    #   register: wsl_status
    #  - name: Run remote PowerShell Script
    #    win_command: powershell.exe -ExecutePolicy ByPass -File c:/temp/powershellscirpt.ps1