---
# This playbook can be used to setup and maintain a local Windows environment

- name: Setup Local Environment
  hosts: windows
  # gather_facts: no
  vars_prompt:
    - name: "ansible_password"
      prompt: "Enter Local Windows Administrator Password"
      private: yes
  roles:
    # - common    
    # - powershellcore
    - windows
    # - extra
    - development