---
- name: Get Fontforge Repository
  shell: apt-get install -y fontforge
- name: Install apt package FontForge
  apt:
    state: latest
    pkg: fontforge
  tags:
    - fontforge
    - software-installation
    - using-apt
- name: Install apt package python3-fontforge
  apt:
    state: latest
    pkg: python3-fontforge
  tags:
    - python-fontforge
    - software-installation
    - using-apt
- name: Install Font Patcher
  get_url:
    url: https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/font-patcher
    dest: '{{ systemdrive_temp }}/font-patcher'
- name: Install apt package ZSH
  apt:
    state: latest
    pkg: zsh
# - name: Remove powerlevel10k Theme
#   shell: rm -r $ZSH_CUSTOM/themes/powerlevel10k
- name: Install powerlevel10k on Oh My Zsh
  shell: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
  become: yes  
- name: Install apt package Powerline Fonts
  apt:
    state: latest
    pkg: fonts-powerline