---
- name: Install all security, critical, and rollup updates without a scheduled task
  win_updates:
    category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
        
# - name: Install Microsoft Subsystem for Linux
#   win_optional_feature:
#     name: Microsoft-Windows-Subsystem-Linux
#     state: present
#   register: wsl_status
# - name: Run remote PowerShell Script
#   win_command: powershell.exe -ExecutePolicy ByPass -File c:/temp/powershellscirpt.ps1

- name: Install .NET SDK latest version
  win_chocolatey:
    name: dotnetcore-sdk
    state: latest